Fix docs + new workflows
logzio/micrometer-registry-logzio pull request #8
Opened 2021-11-03 10:08 UTC by yotamloe

2021-11-09 20:51 UTC, Doron-Bargo requested changes
Great work
Some cosmetics comments

2021-11-09 20:51 UTC, Doron-Bargo commented on README.md
> +            // return "https://listener.logz.io:5053";
return "https://<<listener-url>>:8053";
Also the example should be with port 8053

2021-11-09 20:51 UTC, Doron-Bargo commented on build.gradle
> +//uploadArchives {
why we need this code in comment?

2021-12-06 09:26 UTC, yotamloe commented
changes in this PR are included in #7. closing for now

2021-12-06 09:26 UTC, closed without merging